FlowerAndGiftShop/FlowerAndGiftShop/Controllers/FlowersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FlowerAndGiftShop.DataAccessLayer;
using FlowerAndGiftShop.Models;
using System.IO;
using FlowerAndGiftShop.ViewModels;
using System.Web.Security;
using Microsoft.AspNet.Identity;

namespace FlowerAndGiftShop.Controllers
{
    public class FlowersController : Controller
    {
        #region PROPERTIES
        #endregion

        #region CONSTRUCTORS
        private FlowerAndGiftShopContext db = new FlowerAndGiftShopContext();
        #endregion

        #region GET METHODS
        [Authorize(Roles = "admin, employee")]
        public ActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "admin, employee")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Flower flower = db.Flower.Find(id);
            if (flower == null)
            {
                return HttpNotFound();
            }
            return View(flower);
        }

        [Authorize(Roles = "admin, employee")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Flower flower = db.Flower.Find(id);
            if (flower == null)
            {
                return HttpNotFound();
            }
            return View(flower);
        }

        public ActionResult Index(string typeFlower, string searchedText)
        {
           

            var flowers = from f in db.Flower
                          select f;

            if (!String.IsNullOrEmpty(typeFlower))
            {
                flowers = db.Flower.Where(s => s.Type.Contains(typeFlower));
            }

            if (!String.IsNullOrEmpty(searchedText))
            {
                searchedText = searchedText.ToLower();
                flowers = db.Flower.Where(s => s.Type.ToLower().Contains(searchedText) || s.Name.ToLower().Contains(searchedText));
            }

            string userID = User.Identity.GetUserId();
            if (userID != null)
            {
                Customer cust = (Customer)db.Customer.Where(s => s.UserID.Equals(userID)).FirstOrDefault();
                ViewBag.UserType = (cust != null) ? "customer" : "employee";
            }
            else
            {
                ViewBag.UserType = "unauthorized";
            }     
            return View(flowers.ToList());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FlowerOrder flowerOrder = new FlowerOrder();
            Flower flower = db.Flower.Find(id);
            if (flower == null)
            {
                return HttpNotFound();
            }
            flowerOrder.Flower = flower;

            string userID = User.Identity.GetUserId();
            if (userID != null)
            {
                Customer cust = (Customer)db.Customer.Where(s => s.UserID.Equals(userID)).FirstOrDefault();
                ViewBag.UserType = (cust != null) ? "customer" : "employee";
            }
            else
            {
                ViewBag.UserType = "unauthorized";
            }     

            return View(flowerOrder);

        }

        [Authorize]
        public ActionResult AddToCart(int flowerID)
        {
            string userID = User.Identity.GetUserId();
            Customer customer = (Customer)db.Customer.Where(s => s.UserID.Equals(userID)).FirstOrDefault();
            Flower flower = db.Flower.Find(flowerID);
            if (flower == null)
            {
                return HttpNotFound();
            }

            ShopCart shopCart = new ShopCart();
            shopCart.CustomerID = customer.ID;
            shopCart.ItemID = flower.ID;
            shopCart.ItemType = "Flower";
            shopCart.ItemName = flower.Name;
            shopCart.Price = flower.Price;

            db.ShopCart.Add(shopCart);
            db.SaveChanges();
            return RedirectToAction("../ShopCart/Index");
        }
        #endregion

        #region POST METHODS
        [Authorize(Roles = "admin, employee")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Flower flower, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    file.SaveAs(HttpContext.Server.MapPath("~/Images/Flowers/") + file.FileName);
                    string fileName = "Images/Flowers/" + file.FileName;
                    flower.Image = fileName;
                }

                db.Flower.Add(flower);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(flower);
        }

        [Authorize(Roles = "admin, employee")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Flower flower, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    file.SaveAs(HttpContext.Server.MapPath("~/Images/Flowers/") + file.FileName);
                    string fileName = "Images/Flowers/" + file.FileName;
                    flower.Image = fileName;
                }

                db.Entry(flower).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(flower);
        }

        [Authorize(Roles = "admin, employee")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Flower flower = db.Flower.Find(id);
            db.Flower.Remove(flower);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpPost]
        public ActionResult BuyItem(FlowerOrder flowerOrder, string command)
        {            
                int itemID = flowerOrder.Flower.ID;
                var errors = ModelState
                    .Where(x => x.Value.Errors.Count > 0)
                    .Select(x => new { x.Key, x.Value.Errors })
                    .ToArray();
                if (ModelState.IsValid)
                {
                    Order order = new Order();
                    itemID = (int)flowerOrder.Flower.ID;
                    Flower flower = db.Flower.Find(itemID);
                    if (flower == null)
                    {
                        return HttpNotFound();
                    }
                    flowerOrder.Flower = flower;
                    order.CustomerID = User.Identity.GetUserId();
                    order.ItemType = "Flower";
                    order.ItemName = flower.Name;
                    order.ItemID = itemID;
                    order.DateOrdered = DateTime.Now;
                    //DateTime date;
                    //date.Date = flowerOrder.Order.DateCompleted.Date;
                    //date.Add = int.Parse(timeOrder.ToString().Split(':')[0]);
                    order.DateCompleted = flowerOrder.Order.DateCompleted.Date;
                    order.Description = flowerOrder.Order.Description;
                    order.Price = flower.Price;
                    order.Sale = flowerOrder.Order.Sale * order.Price / 100;
                    order.TotalPrice = order.Price - (flowerOrder.Order.Sale * order.Price / 100);

                    if (flowerOrder.Order.Quantity > 0)
                    {
                        order.Quantity = flowerOrder.Order.Quantity;
                        if (order.Quantity > flowerOrder.Flower.Quantity)
                        {
                            TempData["notice"] = "You must select smaller number of items!!!";
                            return RedirectToAction("Details/" + itemID);
                        }
                        flower.Quantity = flower.Quantity - order.Quantity;
                        order.TotalPrice = order.TotalPrice * order.Quantity;
                    }
                    order.Delivery = flowerOrder.Order.Delivery;
                    if (flowerOrder.Order.Delivery)
                        if (flowerOrder.Order.PlaceDelivery != null)
                        {
                            order.PlaceDelivery = flowerOrder.Order.PlaceDelivery;
                        }

                    string controllerName = "Flower";
                    if (command == "Buy Item")
                    {
                        order.OrderStatusID = 1;
                        controllerName = "Orders";
                    }
                    else if (command == "Add To Cart")  //into order packages
                    {
                        order.OrderStatusID = 6;
                        controllerName = "OrderPackages";
                    }

                    try
                    {
                        db.Order.Add(order);
                        db.Entry(flower).State = EntityState.Modified;
                        db.SaveChanges();
                        if (command == "Add To Cart")  //into order packages
                        {
                            OrderPackages orderPackage = new OrderPackages();
                            orderPackage.OrderID = order.ID;
                            orderPackage.CustomerID = User.Identity.GetUserId();
                            orderPackage.DateOrdered = DateTime.Now;
                            db.OrderPackages.Add(orderPackage);
                        }

                        db.SaveChanges();
                    }

FlowerAndGiftShop/FlowerAndGiftShop/Views/Flowers/Create.cshtml
@model FlowerAndGiftShop.Models.Flower

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Create";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")


    @using (Html.BeginForm("Create", "Flowers", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Flower</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            @*<div class="form-group">
                    @Html.Label("Translated Name", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.NameTranslation, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.NameTranslation, "", new { @class = "text-danger" })
                    </div>
                </div>*@

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>
            @*<div class="form-group">
                    @Html.Label("Translated Description", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DescriptionTranslation, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DescriptionTranslation, "", new { @class = "text-danger" })
                    </div>
                </div>*@

            <div class="form-group">
                @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.Label("Keywords", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <p><input type="file" name="file" value="Upload" /></p>
                    <p>
                        <input type="submit" value="Create" class="btn btn-success" /> |
                        @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-info" })
                    </p>
                </div>
            </div>

        </div>
    }
</body>
</html>

FlowerAndGiftShop/FlowerAndGiftShop/Views/Flowers/Delete.cshtml
@model FlowerAndGiftShop.Models.Flower

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Flower</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Quantity)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Quantity)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Type)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Type)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Price)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Price)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Image)
            </dt>
    
            <dd>
                <img src="@Html.DisplayFor(model => model.Image)" alt="@Html.DisplayFor(model => model.Name)" height="210" width="180" />
            </dd>
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

FlowerAndGiftShop/FlowerAndGiftShop/Views/Flowers/Details.cshtml
@model FlowerAndGiftShop.ViewModels.FlowerOrder
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
    <meta name="viewport" content="width=device-width" />
    @section scripts {
        <script>
            $(document).ready(function () {
                $(".datepicker").datepicker({
                    dateFormat: "dd/MM/yy"
                });
            });
        </script>        
    }
    <style type="text/css">
        .ui-widget-header {
            background: #EB6864;
            border: 1px solid #EB6864;
            color: #EEE;
        }

        .ui-state-highlight {
            border: 1px solid #1A873A;
            background: #1A873A;
        }
    </style>

</head>
<body>
    <div>
        <h2>@Model.Flower.Name</h2>
        <hr />
        @using (Html.BeginForm("BuyItem", "Flowers", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.HiddenFor(model => Model.Flower.ID)
            <table style="display:block; float:left; width:320px;">
                <tr>
                    <td colspan="2">
                        @{
                            string imagePath = "../../" + @Model.Flower.Image;
                        }
                        <img src="@imagePath" alt="@Model.Flower.Name" height="400" width="400" />
                    </td>
                </tr>
                <tr style ="height:30px;"></tr>
                @if (ViewBag.UserType == "customer")
                {
                    <tr>
                        <td>
                            @Html.ActionLink("Add To Favorites", "AddtoCart", new { flowerID = Model.Flower.ID }, new { @class = "btn btn-primary" })
                        </td>
                        <td>
                            <input type="submit" id="btnCart" name="command" value="Add To Cart" class="btn btn-primary" style="display:block; float: right;" />
                        </td>
                    </tr>
                }                
                @if (ViewBag.UserType == "employee")
                {
                    <tr>
                        <td>
                            <div style="display:block; float:left; width:200px; clear:both; margin-top: 20px;">
                                @Html.ActionLink("Edit", "Edit", new { id = Model.Flower.ID }, new { @class = "btn btn-info" }) |
                                @Html.ActionLink("Delete", "Delete", new { id = Model.Flower.ID }, new { @class = "btn btn-info" })
                            </div>
                        </td>
                        <td></td>
                    </tr>                    
                }  
                <tr>
                    <td>
                        <div style="display:block; float:left; width:200px; clear:both; margin-top: 20px;">
                            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-info" })
                        </div>
                    </td>
                </tr>              
            </table>

            <table style="display:block; float:right; clear:right; width: 600px; text-align: justify; padding-left: 120px;">
                <tr style="border-bottom: dotted 1px gray">
                    <td colspan="2">
                        @Html.DisplayFor(model => model.Flower.Description)
                    </td>
                </tr>
                <tr style="height:50px">
                    <td style ="width:190px">&nbsp;</td>
                <tr />
                <tr>
                    <td>
                        Price: @Html.DisplayFor(model => model.Flower.Price) den
                    </td>
                    <td>
                        Number of available pieces: @Html.DisplayFor(model => model.Flower.Quantity)
                    </td>
                </tr>
                <tr style="border-bottom: dotted 1px gray;">
                    
                </tr>
                <tr style="height:50px">
                    <td>&nbsp;</td>
                <tr />
                <tr>
                    <td>
                        Select quantity:
                    </td>
                    <td>
                        Include delivery: @Html.CheckBoxFor(model => model.Order.Delivery)
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.TextBoxFor(model => model.Order.Quantity, "", new { style = "width:25px;height:25px" }) / @Html.DisplayFor(model => model.Flower.Quantity)
                    </td>
                    <td>
                        Delivery address:
                    </td>
                </tr>
                <tr>
                    <td>
                        <div>
                            Date:
                        </div>
                        <div class="editor-field">
                            @Html.TextBoxFor(model => model.Order.DateCompleted, @DateTime.Now.ToString(), new { @class = "datepicker" })
                        </div>
                        @*<div>
                            Time:
                        </div>
                        <div class="editor-field">
                            <input value="8:00am" class="timepicker" name="timeOrder" type="text" onchange="timePickerFunction()">
                        </div>*@
                    </td>
                    <td>
                        @Html.TextAreaFor(model => model.Order.PlaceDelivery, 4, 30, null)
                    </td>
                </tr>
                <tr style="height:20px">
                    <td>&nbsp;</td>
                <tr />
                <tr>
                    <td>
                        
                    </td>
                    <td>
                        Note:
                    </td>
                </tr>
                <tr>
                    <td style="vertical-align: top;"> 
                        @if (ViewBag.UserType != "employee")
                        {
                            <input type="submit" id="btnBuy" name="command" value="Buy Item" class="btn btn-success" />
                        }                       
                    </td>
                    <td>
                        @Html.TextAreaFor(model => model.Order.Description, 4, 30, null)
                    </td>
                </tr>
                @if (TempData["notice"] != null)
                {
                    <tr>
                        <td style="vertical-align: top;">
                            <p>@TempData["notice"]</p>
                        </td>
                    </tr>
                }
                @if (TempData["authentication"] != null)
                {
                    <tr>
                        <td style="vertical-align: top; color:red">
                            <h2>@TempData["authentication"]</h2>
                        </td>
                    </tr>
                }
            </table>
        }
    </div>
</body>

FlowerAndGiftShop/FlowerAndGiftShop/Views/Flowers/Edit.cshtml
@model FlowerAndGiftShop.Models.Flower

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Edit";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    
    
    @using (Html.BeginForm("Edit", "Flowers", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Flower</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ID)
    
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.Label("Keywords", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                  @* @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" }) *@  
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
                </div>                
            </div>

            @*<div class="form-group" id="picture">
                <img src="@Model.Image" alt="Flower" height="210" width="180" />
            </div>*@

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <p><input type="file" name="file" value="Upload" /></p>
                    <input type="submit" value="Save" class="btn btn-success" />
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })
                </div>
            </div>

            </div>
    }
    
    
</body>
</html>

FlowerAndGiftShop/FlowerAndGiftShop/Views/Flowers/Index.cshtml
@model IEnumerable<FlowerAndGiftShop.Models.Flower>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Flowers";
    var count = 0;
    var tr = new HtmlString("<tr>");
    var trclose = new HtmlString("</tr>");
}

<h2>Flowers</h2>
@if (ViewBag.UserType == "employee")
{
    <p style="margin-top: 30px;">
        @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-success" })
    </p>
}
    <table class="table">     
        <tr>
            @foreach (var item in Model)
            {
                <td style="width: 200px;">
                    <img src="../@item.Image" alt="@item.Name" height="210" width="180" />
                </td>
                <td>
                    <div style="height: 145px">
                        @Html.DisplayFor(modelItem => item.Name)
                        <br />
                        @Html.DisplayFor(modelItem => item.Price) den.
                        <br />
                    </div>

                   <div style="display: block; height: 60px">
                       @Html.ActionLink("Details", "Details", new { id = item.ID }, new { @class = "btn btn-primary", @style = "" })
                       <br />
                       @if (ViewBag.UserType == "employee")
                       {
                           @*<div id="adminControls" style="margin-top: 5px;">
                                @Html.ActionLink("Edit", "Edit", new { id = item.ID }, new { @class = "btn btn-info btn-xs" }) |
                                @Html.ActionLink("Delete", "Delete", new { id = item.ID }, new { @class = "btn btn-info btn-xs" })
                            </div>*@
                       }   
                   </div>                   
                </td>               
               
                count++;
                if(count%3==0)
                {
                    @trclose;
                    @tr;
                }

              }
        </tr>
    </table>