FlowerAndGiftShop/FlowerAndGiftShop/Controllers/OrderPackagesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FlowerAndGiftShop.DataAccessLayer;
using FlowerAndGiftShop.Models;
using System.Web.Security;
using Microsoft.AspNet.Identity;

namespace FlowerAndGiftShop.Controllers
{
    public class OrderPackagesController : Controller
    {
        #region CONSTRUCTOR
        private FlowerAndGiftShopContext db = new FlowerAndGiftShopContext();
        #endregion

        #region GET METHODS
        // GET: OrderPackages
        [Authorize]
        public ActionResult Index()
        {
            string userID = User.Identity.GetUserId();
            Customer cust = (Customer)db.Customer.Where(s => s.UserID.Equals(userID)).FirstOrDefault();
            if (cust != null)
            {
                ViewBag.UserType = "customer";
            }
            else
            {
                ViewBag.UserType = "employee";
            }
            IQueryable<OrderPackages> orderPackages = db.OrderPackages.Where(s => s.CustomerID.Contains(userID));
            List<Order> ordersForView = new List<Order>();
            foreach (var order in orderPackages)
            {
                Order newOrder = (Order) db.Order.Where(o => o.ID == order.OrderID && o.OrderStatusID == 6).FirstOrDefault();
                if (newOrder != null)
                {
                    ordersForView.Add(newOrder);
                    ViewBag.customerShopCart = newOrder;
                }
            }

            return View(ordersForView);
            //return View(db.Order.ToList());
        }

        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Order.Find(id);            
            Customer cust = (Customer)db.Customer.Where(s => s.UserID.Equals(order.CustomerID)).FirstOrDefault();
            if (cust != null)
            {
                ViewBag.UserType = "customer";
            }
            else
            {
                ViewBag.UserType = "employee";
            }
            ViewBag.StatusOrderItem = db.OrderStatus.Find(order.OrderStatusID);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        [Authorize]
        public ActionResult Remove(int id)
        {
            Order order = db.Order.Find(id);
            order.OrderStatusID = 4;
            db.Entry(order).State = EntityState.Modified;

            //where condition for orderID
            OrderPackages orderPackage = db.OrderPackages.Where(o => o.OrderID == order.ID).FirstOrDefault();
            db.OrderPackages.Remove(orderPackage);
            db.SaveChanges();

            //TODO: send message for successfully removed item
            return RedirectToAction("Index");
        }

        [Authorize]
        public ActionResult BuyItem(int id)
        {         
            Order order = db.Order.Find(id);
            order.OrderStatusID = 1;
            db.Entry(order).State = EntityState.Modified;

            OrderPackages orderPackage = db.OrderPackages.Where(o => o.OrderID == order.ID).FirstOrDefault();
            db.OrderPackages.Remove(orderPackage);
            db.SaveChanges();

            //TODO: send message for successfully buyed item
            return RedirectToAction("../Orders/Index");
        }

        [Authorize]
        public ActionResult BuyAllItems(string ids)
        {
            var listIds = ids.Split(',');
            
            foreach (var id in listIds){
                if (id != "0" && id != null && id != "")
                {
                    Order order = db.Order.Find(int.Parse(id));
                    order.OrderStatusID = 1;
                    db.Entry(order).State = EntityState.Modified;

                    OrderPackages orderPackage = db.OrderPackages.Where(o => o.OrderID == order.ID).FirstOrDefault();
                    db.OrderPackages.Remove(orderPackage);
                    db.SaveChanges();
                }
            }
            //TODO: send message for successfully buyed items
            return RedirectToAction("Index");
        }
        #endregion

        #region HELPER METHODS
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        #endregion
    }
}

FlowerAndGiftShop/FlowerAndGiftShop/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FlowerAndGiftShop.DataAccessLayer;
using FlowerAndGiftShop.Models;
using FlowerAndGiftShop.ViewModels;
using System.Web.Security;
using Microsoft.AspNet.Identity;

namespace FlowerAndGiftShop.Controllers
{
    public class OrdersController : Controller
    {
        #region PROPERTIES
        #endregion

        #region CONSTRUCTORS
        private FlowerAndGiftShopContext db = new FlowerAndGiftShopContext();
        #endregion

        #region GET METHODS

        [Authorize(Roles = "admin, employee")]
        public ActionResult Create()
        {
            string userID = User.Identity.GetUserId();
            if (userID != null)
            {
                Customer cust = (Customer)db.Customer.Where(s => s.UserID.Equals(userID)).FirstOrDefault();
                ViewBag.UserType = (cust != null) ? "customer" : "employee";
            }
            else
            {
                ViewBag.UserType = "unauthorized";
            } 
            return View();
        }

        [Authorize(Roles = "admin, employee")]
        public ActionResult Edit(int? id)
        {
            string userID = User.Identity.GetUserId();
            if (userID != null)
            {
                Customer cust = (Customer)db.Customer.Where(s => s.UserID.Equals(userID)).FirstOrDefault();
                ViewBag.UserType = (cust != null) ? "customer" : "employee";
            }
            else
            {
                ViewBag.UserType = "unauthorized";
            } 
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Order.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        [Authorize(Roles = "admin, employee")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Order.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        [Authorize(Roles = "employee")]
        public ActionResult Complete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Order.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            order.OrderStatusID = 2;
            order.HasCompleted = true;
            db.Entry(order).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "customer")]
        public ActionResult Index(int? status)
        {
            string userID = User.Identity.GetUserId();
            if (userID != null)
            {
                Customer cust = (Customer)db.Customer.Where(s => s.UserID.Equals(userID)).FirstOrDefault();
                ViewBag.UserType = (cust != null) ? "customer" : "employee";
            }
            else
            {
                ViewBag.UserType = "unauthorized";
            }     
            var orders = db.Order.Where(s => s.CustomerID.Contains(userID) 
                                                && s.OrderStatusID != 4
                                                && s.OrderStatusID != 5
                                                && s.OrderStatusID != 6);
            
            if (status == 1 || status == 2 || status == 7)
            {
                orders = db.Order.Where(s => s.CustomerID.Contains(userID) 
                                        && s.OrderStatusID == status);
            }

            ViewBag.selectedStatus = status;
            return View(orders);
        }

        [Authorize(Roles = "employee")]
        public ActionResult AllOrders(int? status)
        {
            string userID = User.Identity.GetUserId();
            if (userID != null)
            {
                Customer cust = (Customer)db.Customer.Where(s => s.UserID.Equals(userID)).FirstOrDefault();
                ViewBag.UserType = (cust != null) ? "customer" : "employee";
            }
            else
            {
                ViewBag.UserType = "unauthorized";
            }     
            var orders = db.Order.Where(s => s.OrderStatusID != 4
                                                && s.OrderStatusID != 5
                                                && s.OrderStatusID != 6);

            if (status == 1 || status == 2 || status == 7)
            {
                orders = db.Order.Where(s => s.OrderStatusID == status);
            }

            ViewBag.selectedStatus = status;
            return View(orders);
        }

        [Authorize(Roles = "employee")]
        public ActionResult AllOrdersByStatus(int status)
        {
            string userID = User.Identity.GetUserId();
            if (userID != null)
            {
                Customer cust = (Customer)db.Customer.Where(s => s.UserID.Equals(userID)).FirstOrDefault();
                ViewBag.UserType = (cust != null) ? "customer" : "employee";
            }
            else
            {
                ViewBag.UserType = "unauthorized";
            }

            var orders = db.Order.Where(s => s.OrderStatusID != 4
                                                && s.OrderStatusID != 5
                                                && s.OrderStatusID != 6);

            if (status == 1 || status == 2)
            {
                orders = db.Order.Where(s => s.OrderStatusID == status);
            }
            return RedirectToAction("AllOrders", new { model = orders });
            //return View("AllOrders", orders);
        }

        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CustomerOrder customerOrder = new CustomerOrder();
            Order order = db.Order.Find(id);
            customerOrder.Order = order;

            string userID = User.Identity.GetUserId();
            if (userID != null)
            {
                Customer cust = (Customer)db.Customer.Where(s => s.UserID.Equals(userID)).FirstOrDefault();
                ViewBag.UserType = (cust != null) ? "customer" : "employee";
            }
            else
            {
                ViewBag.UserType = "unauthorized";
            } 

            if (order.ItemType.Equals("Flower"))
            {
                customerOrder.Flower = db.Flower.Find(order.ItemID);
            }
            else if (order.ItemType.Equals("Product"))
            {
                customerOrder.Product = db.Product.Find(order.ItemID);
            }
            else if (order.ItemType.Equals("Service"))
            {
                customerOrder.Service = db.Service.Find(order.ItemID);
            }
            else
            {
                return HttpNotFound();
            }
            ViewBag.StatusOrderItem = db.OrderStatus.Find(order.OrderStatusID);
            //TempData["ItemType"] = order.ItemType;

            if (order == null)
            {
                return HttpNotFound();
            }
            return View(customerOrder);
        }

        [Authorize(Roles = "customer")]
        public ActionResult Cancel(int id)
        {
            Order order = db.Order.Find(id);
            order.OrderStatusID = 3;
            order.HasCompleted = true;
            db.Entry(order).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
                
        public ActionResult Remove(int id)
        {
            Order order = db.Order.Find(id);
            order.OrderStatusID = 4;  //Remove from list - set as deleted
            order.HasCompleted = true;
            db.Entry(order).State = EntityState.Modified;
            db.SaveChanges();

            string userID = User.Identity.GetUserId();
            if (userID != null)
            {
                Customer cust = (Customer)db.Customer.Where(s => s.UserID.Equals(userID)).FirstOrDefault();
                ViewBag.UserType = (cust != null) ? "customer" : "employee";
            }
            else
            {
                ViewBag.UserType = "unauthorized";
            }

            if (ViewBag.UserType == "customer")
            {
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("AllOrders");
            }
            //return RedirectToAction("Index");
        }
        
        public ActionResult Reject(int id)
        {
            Order order = db.Order.Find(id);
            order.OrderStatusID = 7; 
            order.HasCompleted = true;
            db.Entry(order).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("AllOrders");
        }
        
        public ActionResult SetCompleted(int id)
        {
            Order order = db.Order.Find(id);
            order.OrderStatusID = 2; 
            order.HasCompleted = true;
            db.Entry(order).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("AllOrders");
        }        
        #endregion

        #region POST METHODS
        [Authorize(Roles = "admin, employee")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Order order)
        {
            if (ModelState.IsValid)
            {
                order.OrderStatusID = 1;

FlowerAndGiftShop/FlowerAndGiftShop/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Globalization;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace FlowerAndGiftShop.Controllers
{
    public class SharedController : Controller
    {
        public void ChangeLanguage(string language, string isUserAuthorized)
        {
            Thread.CurrentThread.CurrentCulture = CultureInfo.CreateSpecificCulture(language ?? "en-EN");
            Thread.CurrentThread.CurrentUICulture = new CultureInfo(language ?? "en-EN");

            CultureInfo tempCulture = (CultureInfo)CultureInfo.CurrentUICulture.Clone();

            tempCulture.NumberFormat.NumberDecimalSeparator = ".";
            tempCulture.NumberFormat.NumberGroupSeparator = ",";
            tempCulture.NumberFormat.PercentDecimalSeparator = ".";

            System.Threading.Thread.CurrentThread.CurrentUICulture = tempCulture;
            System.Threading.Thread.CurrentThread.CurrentCulture = tempCulture;

            
                Response.Redirect("../Home/Index");
            
                ///Response.Redirect(Request.UrlReferrer.ToString(), true);
        }

         public ActionResult ChangeCulture(string lang, string returnUrl)
         {
              Session["Culture"] = new CultureInfo(lang);
              return Redirect(returnUrl);
         }

        // GET: Shared
        public ActionResult Index()
        {
            return View();
        }

        //public static void SetCurrentCulture(string currentLanguage)
        //{
        //    Thread.CurrentThread.CurrentCulture = CultureInfo.CreateSpecificCulture(currentLanguage ?? ConfigurationManager.AppSettings["DefaultLanguage"]);
        //    Thread.CurrentThread.CurrentUICulture = new CultureInfo(currentLanguage ?? ConfigurationManager.AppSettings["DefaultLanguage"]);

        //    CultureInfo tempCulture = (CultureInfo)CultureInfo.CurrentUICulture.Clone();

        //    tempCulture.NumberFormat.NumberDecimalSeparator = ".";
        //    tempCulture.NumberFormat.NumberGroupSeparator = ",";
        //    tempCulture.NumberFormat.PercentDecimalSeparator = ".";

        //    System.Threading.Thread.CurrentThread.CurrentUICulture = tempCulture;
        //    System.Threading.Thread.CurrentThread.CurrentCulture = tempCulture;
        //}

    }
}

FlowerAndGiftShop/FlowerAndGiftShop/Views/Shared/_LanguagePartial.cshtml
@*<span class="container-znaminja">
    <a title="english" onclick="ChangeLanguage('en-EN','true')">EN</a>
    <a title="македонски" onclick="ChangeLanguage('mk-MK','true')">MK</a>
</span>*@

@Html.ActionLink("English", "ChangeCulture", "Shared",
     new { lang = "en", returnUrl = this.Request.RawUrl }, null)
@Html.ActionLink("MKD", "ChangeCulture", "Shared",
     new { lang = "mk-MK", returnUrl = this.Request.RawUrl }, null)

<script>
    function ChangeLanguage(language, isUserAuthorized) {
        window.location = "/Shared/ChangeLanguage?language=" + language + "&isUserAuthorized=" + isUserAuthorized;
    }
</script>

FlowerAndGiftShop/FlowerAndGiftShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title | Viviano Flower&GiftShop </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link href="~/Content/journalTheme.css" rel="stylesheet" />
    @*<link href="~/Content/unitedTheme.css" rel="stylesheet" />*@

</head>
<body style="background-color: white;">
    <div class="navbar navbar-default navbar-fixed-top" >
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Flowers<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Roses", "Index", "Flowers", new { typeFlower = "Rose" }, null)</li>
                            <li>@Html.ActionLink("Gerbera", "Index", "Flowers", new { typeFlower = "Gerbera" }, null)</li>
                            <li>@Html.ActionLink("Carniations", "Index", "Flowers", new { typeFlower = "Carniation" }, null)</li>
                            <li>@Html.ActionLink("Lilies", "Index", "Flowers", new { typeFlower = "Lilies" }, null)</li>
                            <li>@Html.ActionLink("Bouquets", "Index", "Flowers", new { typeFlower = "Bouquet" }, null)</li>
                            <li class="divider"></li>
                            <li>@Html.ActionLink("All Flowers", "Index", "Flowers", new { typeFlower = "" }, null)</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Gifts<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Sweets", "Index", "Products", new { typeProduct = "Food" }, null)</li>
                            <li>@Html.ActionLink("Wines", "Index", "Products", new { typeProduct = "Wine" }, null)</li>
                            <li>@Html.ActionLink("Teddy Bears", "Index", "Products", new { typeProduct = "Teddy" }, null)</li>
                            <li>@Html.ActionLink("Cards", "Index", "Products", new { typeProduct = "Card" }, null)</li>
                            <li class="divider"></li>
                            <li>@Html.ActionLink("All Gifts", "Index", "Products", new { typeProduct = "" }, null)</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Services<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                            <li>@Html.ActionLink("Promotions", "Promotion", "Services", new { name = "Valentine" }, null)</li>
                            <li>@Html.ActionLink("Decorations", "Index", "Services", new { name = "decoration" }, null)</li>
                            <li class="dropdown-submenu">
                                @Html.ActionLink("Events", "Index", "Services", new { name = "events" }, null)
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Wedding", "Index", "Services", new { name = "wedding" }, null)</li>
                                    <li>@Html.ActionLink("Birthday", "Index", "Services", new { name = "party" }, null)</li>
                                    <li>@Html.ActionLink("Outdoor Party", "Index", "Services", new { name = "outdoor" }, null)</li>
                                    <li>@Html.ActionLink("Christmas", "Index", "Services", new { name = "christmas" }, null)</li>
                                </ul>
                            </li>
                            <li>@Html.ActionLink("Delivery", "Index", "Services", new { name = "Delivery" }, null)</li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    @if (ViewBag.UserType == "customer")
                    {
                        <li>@Html.ActionLink("My Favorites", "Index", "ShopCart")</li>
                        <li>@Html.ActionLink("My Shop Cart", "Index", "OrderPackages")</li>
                        <li>@Html.ActionLink("My Orders", "Index", "Orders")</li>
                    }   
                    @if (ViewBag.UserType == "employee")
                    {
                        <li>@Html.ActionLink("Orders", "AllOrders", "Orders")</li>
                    }   
                </ul>
                @*<div style="display: block; float: right; padding-left: 40px;">
                    @Html.Partial("_LanguagePartial")
                </div>*@
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>

    <div style=" background-color: white; width: 96%; display: inline-block; margin: 30px auto auto 15px;">
        <div class="container body-content" style="width: 78%; display: inline-block; float: left; margin: 30px auto auto 15px;">
            @RenderBody()
        </div>

        <div style="width: 16%; height:700px; border: 0px dotted gray; display: inline-block; text-align: justify; clear: right; margin:60px auto auto 25px;">
            
            <div style="width:100%; display:block; ">
                <form class="navbar-form navbar-left" role="search">
                    <div class="form-group" style="width:60%;">
                        <input type="text" class="form-control" placeholder="Search" name="searchedText">
                    </div>
                    <button type="submit" class="btn btn-default" style="width:25%; margin-left: 17px;"><span class="glyphicon glyphicon-search"></span></button>
                </form>
            </div>

            <div>
                @*<p>Flower & Gift Shop Viviano Logo</p>*@
                <img src="~/Images/logo2.png" width="100%" />
                <br />
            </div>

            <div class="panel panel-primary" style="width:100%; height: 28%; display:block; ">
                <div class="panel-heading">
                    <h3 class="panel-title">Promotions</h3>
                </div>
                <div class="panel-body" >
                    Enjoy at more than 50 products included in Valentine's day promotion!
                </div>
            </div>
            <div class="panel panel-primary" style="width:100%; height: 25%;">
                <div class="panel-heading">
                    <h3 class="panel-title">Delivery</h3>
                </div>
                <div class="panel-body">
                    Free delivery for every order with payment at least 30 minutes after it is created!
                </div>
            </div>
            <div class="panel panel-primary" style="width:100%; height: 25%;">
                <div class="panel-heading">
                    <h3 class="panel-title">Register account</h3>
                </div>
                <div class="panel-body">
                    Still not our member? Register your account for FREE and use our great services!
                </div>
            </div>
        </div>

        <footer style="display: block; clear: both; margin-top: 50px;">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">&copy; @DateTime.Now.Year - Flower & Gift Shop Viviano</h3>
                </div>
                @*<div class="panel-body">
                    Panel content
                </div>*@
            </div>            
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jquery-ui")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>