FlowerAndGiftShop/FlowerAndGiftShop/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FlowerAndGiftShop.DataAccessLayer;
using FlowerAndGiftShop.Models;
using System.Web.Security;
using Microsoft.AspNet.Identity;
using FlowerAndGiftShop.ViewModels;

namespace FlowerAndGiftShop.Controllers
{
    public class ServicesController : Controller
    {
        #region PROPERTIES AND CONSTRUCTORS
        private FlowerAndGiftShopContext db = new FlowerAndGiftShopContext();
        #endregion

        #region GET METHODS
        // GET: Services/Create
        [Authorize(Roles = "admin, employee")]
        public ActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "admin, employee")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Service service = db.Service.Find(id);
            if (service == null)
            {
                return HttpNotFound();
            }
            return View(service);
        }
        
        // GET: Services/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Service service = db.Service.Find(id);
            if (service == null)
            {
                return HttpNotFound();
            }
            return View(service);
        }
        
        // GET: Services
        public ActionResult Index(String name)
        {
            string userID = User.Identity.GetUserId();
            if (userID != null)
            {
                Customer cust = (Customer)db.Customer.Where(s => s.UserID.Equals(userID)).FirstOrDefault();
                ViewBag.UserType = (cust != null) ? "customer" : "employee";
            }
            else
            {
                ViewBag.UserType = "unauthorized";
            }    
 
            return View();
        }

        public ActionResult Promotion(string name)
        {
            var products = from p in db.Product
                           select p;

            if (!String.IsNullOrEmpty(name))
            {
                products = db.Product.Where(s => s.Type.Contains(name));
            }
            string userID = User.Identity.GetUserId();
            if (userID != null)
            {
                Customer cust = (Customer)db.Customer.Where(s => s.UserID.Equals(userID)).FirstOrDefault();
                ViewBag.UserType = (cust != null) ? "customer" : "employee";
            }
            else
            {
                ViewBag.UserType = "unauthorized";
            }
            return View(products.ToList());

        }

        public ActionResult CreatePromotion(string name, int saleValue)
        {
            //TODO: to be implemented
            return RedirectToAction("Index");
        }

        // GET: Services/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Service service = db.Service.Find(id);
            if (service == null)
            {
                return HttpNotFound();
            }
            string userID = User.Identity.GetUserId();
            if (userID != null)
            {
                Customer cust = (Customer)db.Customer.Where(s => s.UserID.Equals(userID)).FirstOrDefault();
                ViewBag.UserType = (cust != null) ? "customer" : "employee";
            }
            else
            {
                ViewBag.UserType = "unauthorized";
            }     
            return View(service);
        }

        [Authorize]
        public ActionResult AddToCart(int serviceID)
        {
            string userID = User.Identity.GetUserId();
            Customer customer = (Customer)db.Customer.Where(s => s.UserID.Equals(userID)).FirstOrDefault();
            Service service = db.Service.Find(serviceID);
            if (service == null)
            {
                return HttpNotFound();
            }

            ShopCart shopCart = new ShopCart();
            shopCart.CustomerID = customer.ID;
            shopCart.ItemID = service.ID;
            shopCart.ItemType = "Service";
            shopCart.ItemName = service.Name;
            shopCart.Price = service.Price;

            db.ShopCart.Add(shopCart);
            db.SaveChanges();
            return RedirectToAction("../ShopCart/Index");
        }
        #endregion

        #region POST METHODS
        [Authorize(Roles = "admin, employee")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Service service, HttpPostedFileBase file)
        {
            
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    file.SaveAs(HttpContext.Server.MapPath("~/Images/Services/") + file.FileName);
                    string fileName = "Images/Services/" + file.FileName;
                    service.Image = fileName;
                }

                db.Service.Add(service);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(service);
        }
       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Description,Type,Price,Image")] Service service)
        {
            if (ModelState.IsValid)
            {
                db.Entry(service).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(service);
        }
        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Service service = db.Service.Find(id);
            db.Service.Remove(service);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpPost]
        public ActionResult BuyItem(CustomerOrder customerOrder)
        {
            int itemID = customerOrder.Product.ID;

            if (ModelState.IsValid)
            {
                Order order = new Order();
                itemID = (int)customerOrder.Product.ID;
                Service service = db.Service.Find(itemID);
                if (service == null)
                {
                    return HttpNotFound();
                }
                customerOrder.Service = service;
                order.CustomerID = User.Identity.GetUserId(); // Membership.GetUser().ProviderUserKey; 
                order.ItemType = "Service";
                order.ItemName = service.Name;
                order.ItemID = itemID;
                order.DateOrdered = DateTime.Now;
                order.DateCompleted = customerOrder.Order.DateCompleted.Date;
                order.Description = customerOrder.Order.Description;
                order.Price = service.Price;
                order.Sale = 0;
                order.TotalPrice = order.Price - (order.Sale / 100 * order.Price);
                order.OrderStatusID = 1;

                if (customerOrder.Order.Quantity > 0)
                {
                    order.Quantity = customerOrder.Order.Quantity;
                    if (order.Quantity > customerOrder.Product.Quantity)
                    {
                        TempData["notice"] = "You must select smaller number of items!!!";
                        return RedirectToAction("Details/" + itemID);
                    }
                    service.Quantity = service.Quantity - order.Quantity;
                }
                order.Delivery = customerOrder.Order.Delivery;
                if (customerOrder.Order.Delivery)
                    if (customerOrder.Order.PlaceDelivery != null)
                    {
                        order.PlaceDelivery = customerOrder.Order.PlaceDelivery;
                    }
                try
                {
                    db.Order.Add(order);
                    db.Entry(service).State = EntityState.Modified;
                    db.SaveChanges();
                }
                catch (Exception e)
                {
                    System.Diagnostics.Debug.WriteLine(e.Message);
                }
            }

            return RedirectToAction("Index", "Orders", new { area = "" });

        }
        #endregion
        

        
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FlowerAndGiftShop/FlowerAndGiftShop/Views/Services/Create.cshtml
@model FlowerAndGiftShop.Models.Service

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Services", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")

    <div class="form-horizontal">
        <h4>Service</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <p><input type="file" name="file" value="Upload" /></p>
                <p><input type="submit" value="Create" /></p>
            </div>
        </div>

    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

FlowerAndGiftShop/FlowerAndGiftShop/Views/Services/Delete.cshtml
@model FlowerAndGiftShop.Models.Service

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Service</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FlowerAndGiftShop/FlowerAndGiftShop/Views/Services/Details.cshtml
@model FlowerAndGiftShop.Models.Service

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Service</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

FlowerAndGiftShop/FlowerAndGiftShop/Views/Services/Edit.cshtml
@model FlowerAndGiftShop.Models.Service

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Service</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FlowerAndGiftShop/FlowerAndGiftShop/Views/Services/Index.cshtml
@model IEnumerable<FlowerAndGiftShop.Models.Service>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (ViewBag.UserType == "employee")
{
    <p style="margin-top: 30px;">
        @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-success" })
    </p>
}
<a name="events"></a>
    <h1>Events & Decorations</h1>

<a name="wedding"></a>
    <div class="row" style="text-align: justify;">
        <h2 style="padding:30px;">Wedding</h2>
        <div class="col-md-4" style="padding:30px; ">            
            <img src="~/Images/Services/Wedding-Decoration-1.jpg" alt="" height="300" width="300" />
        </div>
        <div class="col-md-4" style="padding:30px;">
            <img src="~/Images/Services/Wedding-Decoration-Flowers-1.jpg" alt="" height="300" width="300" />
        </div>
        <div class="col-md-4" style="padding:30px;">
            <img src="~/Images/Services/Wedding-Decorations-12.jpg" alt="" height="300" width="300" />
        </div>
    </div>

<a name="party"></a>
    <div class="row" style="text-align: justify;">
        <h2 style="padding:30px;">Party </h2>
        <div class="col-md-4" style="padding:30px;">
            <img src="~/Images/Services/party3.jpg" alt="" height="300" width="300" />
        </div>  
        <div class="col-md-4" style="padding:30px; ">
            <img src="~/Images/Services/party1.jpg" alt="" height="300" width="300" />
        </div>
        <div class="col-md-4" style="padding:30px;">
            <img src="~/Images/Services/party2.jpg" alt="" height="300" width="300" />
        </div> 
    </div>

<a name="outdoor"></a>
    <div class="row" style="text-align: justify;">
        <h2 style="padding:30px;">Outdoor</h2>
        <div class="col-md-4" style="padding:30px; ">
            <img src="~/Images/Services/out4.jpg" alt="" height="300" width="300" />
        </div>
        <div class="col-md-4" style="padding:30px;">
            <img src="~/Images/Services/out2.jpg" alt="" height="300" width="300" />
        </div>
        <div class="col-md-4" style="padding:30px;">
            <img src="~/Images/Services/out1.jpg" alt="" height="300" width="300" />
        </div>
    </div>

<a name="christmas"></a>
    <div class="row" style="text-align: justify;">
        <h2 style ="padding:30px;">Christmas</h2>
        <div class="col-md-4" style="padding:30px; ">
            <img src="~/Images/Services/chris1.jpg" alt="" height="300" width="300" />
        </div>
        <div class="col-md-4" style="padding:30px;">
            <img src="~/Images/Services/chris3.jpg" alt="" height="300" width="300" />
        </div>
        <div class="col-md-4" style="padding:30px;">
            <img src="~/Images/Services/chris2.jpg" alt="" height="300" width="300" />
        </div>
    </div>

<a name="promotions"></a>
    <div class="row" style="text-align: justify; padding:30px;">
        <h2 style="padding:30px;">Promotions</h2>
            <p>
                This month you can enjoy at more than 50 products included in Valentine's day promotion.
                Stay tuned 'cause many new promotions are coming up - new month, same place!
            </p>
    </div>

<a name="Delivery"></a>
    <div class="row" style="text-align: justify; padding:30px;">
        <h2 style="padding:30px;">Free Delivery</h2>
        <p>>> Free delivery for every order with payment at least 30 minutes after it is created <<</p>
        <p>>> Free delivery for every order which address is less than 30km from our shop address <<</p>
    </div>

<br />
    

FlowerAndGiftShop/FlowerAndGiftShop/Views/Services/Promotion.cshtml
@model IEnumerable<FlowerAndGiftShop.Models.Product>

@{
    ViewBag.Title = "Promotion";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var count = 0;
    var tr = new HtmlString("<tr>");
    var trclose = new HtmlString("</tr>");
    var promotionSale = 40;
}

<h2>Promotion up to @promotionSale%! </h2>

@if (ViewBag.UserType == "employee")
{
    <p style="margin-top: 30px;">
        @*@Html.ActionLink("Create Promotion", "CreatePromotion", null, new { @class = "btn btn-success" })*@
    </p>
}
<table class="table">
    <tr>
        @foreach (var item in Model)
        {
            <td style="width: 200px;">
                <img src="../@item.Image" alt="@item.Name" height="210" width="180" />
            </td>
            <td>
                <div style="height: 145px">
                    @Html.DisplayFor(modelItem => item.Name)
                    <br />
                    @{
            decimal totalPrice = (decimal)item.Price - (item.Price * promotionSale / 100);
                    }
                    <label style="text-decoration: line-through;" class="text-danger">@item.Price den</label>
                    <br />
                    <label class="text-success">@totalPrice den</label>
                    @*@Html.DisplayFor(modelItem => item.Price, null, new { @style="text-decoration: line-through;"}) den.*@
                    <br />
                </div>
                <div style="display: block; height: 60px">
                    @Html.ActionLink("Details", "Details","Products", new { id = item.ID, sale = promotionSale }, new { @class = "btn btn-primary", @style = "" })
                    <br />
                </div>
            </td>
            
            count++;
            if (count % 3 == 0)
            {
                @trclose;
                @tr;
            }
        }
    </tr>
</table>